import type { Question } from "./types";

// ─── FLOW 3: ROOM DETAILS (10 steps) ─────────────────────────────────────────

export const ROOM_QUESTIONS: Question[] = [
  {
    id: "r1",
    flow: "room",
    section: "ROOM DETAILS",
    type: "single-select",
    layout: "split-typewriter",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "WHO LIVES HERE?",
    subtext: "Tell us about your household.",
    autoAdvance: true,
    options: [
      { id: "r1a", label: "JUST ME" },
      { id: "r1b", label: "ME + PARTNER" },
      { id: "r1c", label: "FAMILY WITH YOUNG KIDS (UNDER 8)" },
      { id: "r1d", label: "FAMILY WITH OLDER KIDS (8+)" },
      { id: "r1e", label: "ROOMMATES" },
    ],
  },
  {
    id: "r2",
    flow: "room",
    section: "ROOM DETAILS",
    type: "single-select",
    layout: "magazine-spread",
    bg: "#8A9E9A",
    accent: "#1a1714",
    question: "ANY PETS?",
    autoAdvance: true,
    options: [
      { id: "r2a", label: "SMALL DOG" },
      { id: "r2b", label: "LARGE DOG" },
      { id: "r2c", label: "CAT" },
      { id: "r2d", label: "MULTIPLE PETS" },
      { id: "r2e", label: "NO PETS" },
    ],
  },
  {
    id: "r3",
    flow: "room",
    section: "ROOM DETAILS",
    type: "single-select",
    layout: "vertical-split",
    bg: "#6B7355",
    accent: "#DDD5C4",
    question: "OWNERSHIP",
    subtext: "What freedoms do you have with this space?",
    autoAdvance: true,
    options: [
      { id: "r3a", label: "I OWN, CAN RENOVATE FREELY" },
      { id: "r3b", label: "RENTING, FLEXIBLE LANDLORD" },
      { id: "r3c", label: "RENTING, STRICT LEASE" },
    ],
  },
  {
    id: "r4",
    flow: "room",
    section: "ROOM DETAILS",
    type: "room-size",
    bg: "#B09470",
    accent: "#1a1714",
    question: "ROOM SIZE",
    subtext: "Approximate dimensions help us suggest proportional furniture.",
    options: [
      { id: "r4-sm", label: "SMALL", sublabel: "10 × 10 ft" },
      { id: "r4-st", label: "STANDARD", sublabel: "12 × 12 ft" },
      { id: "r4-lg", label: "LARGE", sublabel: "14 × 16 ft" },
    ],
  },
  {
    id: "r5",
    flow: "room",
    section: "ROOM DETAILS",
    type: "single-select",
    layout: "full-color-split",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "NATURAL LIGHT",
    autoAdvance: true,
    options: [
      { id: "r5a", label: "BRIGHT & SUNNY (SOUTH/WEST FACING)" },
      { id: "r5b", label: "MODERATE" },
      { id: "r5c", label: "DIM (NORTH FACING)" },
      { id: "r5d", label: "VERY DARK (BASEMENT / MINIMAL WINDOWS)" },
    ],
  },
  {
    id: "r6",
    flow: "room",
    section: "ROOM DETAILS",
    type: "openings",
    bg: "#1a1714",
    accent: "#DDD5C4",
    question: "DOORS & WINDOWS",
    subtext: "Add each opening in the room so we can plan the layout.",
  },
  {
    id: "r7",
    flow: "room",
    section: "ROOM DETAILS",
    type: "multi-select",
    layout: "pinboard",
    bg: "#6B7355",
    accent: "#DDD5C4",
    question: "ROOM FEATURES",
    subtext: "Select any features that apply.",
    optional: true,
    options: [
      { id: "r7a", label: "FIREPLACE" },
      { id: "r7b", label: "BALCONY" },
      { id: "r7c", label: "BUILT IN SHELVES" },
      { id: "r7d", label: "ALCOVE / NOOK" },
      { id: "r7e", label: "COLUMN / PILLAR" },
      { id: "r7f", label: "STAIRCASE" },
      { id: "r7g", label: "RADIATOR" },
      { id: "r7h", label: "FLOOR VENTS" },
      { id: "r7i", label: "EXPOSED PIPES/DUCTWORK" },
    ],
  },
  {
    id: "r8",
    flow: "room",
    section: "ROOM DETAILS",
    type: "single-select",
    layout: "two-column-grid",
    bg: "#B09470",
    accent: "#1a1714",
    question: "FLOORING",
    autoAdvance: true,
    options: [
      { id: "r8a", label: "HARDWOOD" },
      { id: "r8b", label: "CARPET" },
      { id: "r8c", label: "TILE & STONE" },
      { id: "r8d", label: "CONCRETE" },
      { id: "r8e", label: "VINYL & LAMINATE" },
    ],
  },
  {
    id: "r9",
    flow: "room",
    section: "ROOM DETAILS",
    type: "multi-select",
    layout: "hover-reactive",
    bg: "#8A9E9A",
    accent: "#1a1714",
    question: "HOW DO YOU USE THIS ROOM?",
    subtext: "Pick everything that applies.",
    options: [
      { id: "r9a", label: "WATCHING TV / MOVIES" },
      { id: "r9b", label: "READING" },
      { id: "r9c", label: "WORKING / STUDYING" },
      { id: "r9d", label: "EATING MEALS" },
      { id: "r9e", label: "HOSTING FRIENDS" },
      { id: "r9f", label: "KIDS PLAYING" },
      { id: "r9g", label: "EXERCISE / YOGA" },
      { id: "r9h", label: "GAMING" },
      { id: "r9i", label: "NAPPING" },
      { id: "r9j", label: "PLAYING MUSIC" },
      { id: "r9k", label: "VIDEO CALLS" },
    ],
  },
  {
    id: "r10",
    flow: "room",
    section: "ROOM DETAILS",
    type: "grouped-checklist",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "FURNITURE NEEDS",
    subtext: "Check everything you need for this room.",
    checklistGroups: [
      {
        id: "seating",
        label: "SEATING",
        items: [
          { id: "r10-sofa", label: "SOFA" },
          { id: "r10-armchair", label: "ARMCHAIR" },
          { id: "r10-ottoman", label: "OTTOMAN" },
          { id: "r10-bench", label: "BENCH" },
        ],
      },
      {
        id: "tables",
        label: "TABLES",
        items: [
          { id: "r10-coffee", label: "COFFEE TABLE" },
          { id: "r10-dining", label: "DINING TABLE" },
          { id: "r10-side", label: "SIDE TABLE" },
          { id: "r10-desk", label: "DESK" },
          { id: "r10-console", label: "CONSOLE TABLE" },
        ],
      },
      {
        id: "storage",
        label: "STORAGE",
        items: [
          { id: "r10-shelf", label: "BOOKSHELF" },
          { id: "r10-tv", label: "TV STAND" },
          { id: "r10-wardrobe", label: "WARDROBE" },
          { id: "r10-dresser", label: "DRESSER" },
          { id: "r10-nightstand", label: "NIGHTSTAND" },
        ],
      },
      {
        id: "sleep",
        label: "SLEEP",
        items: [{ id: "r10-bed", label: "BED" }],
      },
      {
        id: "lighting",
        label: "LIGHTING",
        items: [
          { id: "r10-floor-lamp", label: "FLOOR LAMP" },
          { id: "r10-table-lamp", label: "TABLE LAMP" },
          { id: "r10-pendant", label: "PENDANT/CEILING LIGHT" },
        ],
      },
      {
        id: "decor",
        label: "DECOR",
        items: [
          { id: "r10-rug", label: "AREA RUG" },
          { id: "r10-plants", label: "PLANTS" },
          { id: "r10-mirror", label: "MIRROR" },
          { id: "r10-curtains", label: "CURTAINS/DRAPES" },
        ],
      },
    ],
  },
];
