import type { Question } from "./types";
import { styleExplorerGridImage } from "./style-explorer-image-pool";

// ─── FLOW 1: STYLE DISCOVERY (14 questions) ──────────────────────────────────

export const STYLE_QUESTIONS: Question[] = [
  // Q1 — First Feeling
  {
    id: "s1",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "image-grid",
    layout: "full-color-split",
    bg: "#6B7355",
    accent: "#DDD5C4",
    question: "FIRST FEELING",
    subtext: "Pick 2 to 3 spaces that instantly feel right to you.",
    minSelect: 2,
    maxSelect: 3,
    imageOptions: [
      {
        id: "s1a",
        label: "COZY NOOK",
        imageSrc: styleExplorerGridImage(0),
        unsplashQuery: "cozy reading nook interior",
        style: "organic",
      },
      {
        id: "s1b",
        label: "OPEN LOFT",
        imageSrc: styleExplorerGridImage(1),
        unsplashQuery: "open loft apartment interior",
        style: "industrial",
      },
      {
        id: "s1c",
        label: "MINIMAL STUDIO",
        imageSrc: styleExplorerGridImage(2),
        unsplashQuery: "minimal studio apartment interior",
        style: "minimal",
      },
      {
        id: "s1d",
        label: "WARM LIBRARY",
        imageSrc: styleExplorerGridImage(3),
        unsplashQuery: "warm home library interior books",
        style: "maximalist",
      },
      {
        id: "s1e",
        label: "SUNNY BALCONY",
        imageSrc: styleExplorerGridImage(4),
        unsplashQuery: "sunny balcony outdoor interior",
        style: "organic",
      },
      {
        id: "s1f",
        label: "SERENE BEDROOM",
        imageSrc: styleExplorerGridImage(5),
        unsplashQuery: "serene minimal bedroom interior",
        style: "minimal",
      },
    ],
  },

  // Q2 — Mood Words
  {
    id: "s2",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "multi-select",
    layout: "scattered-chips",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "MOOD WORDS",
    subtext: "Pick 4 to 6 words that describe how you want to feel at home.",
    minSelect: 4,
    maxSelect: 6,
    options: [
      { id: "s2-calm", label: "CALM", style: "minimal" },
      { id: "s2-cozy", label: "COZY", style: "organic" },
      { id: "s2-airy", label: "AIRY", style: "minimal" },
      { id: "s2-grounded", label: "GROUNDED", style: "industrial" },
      { id: "s2-warm", label: "WARM", style: "organic" },
      { id: "s2-minimal", label: "MINIMAL", style: "minimal" },
      { id: "s2-layered", label: "LAYERED", style: "maximalist" },
      { id: "s2-bright", label: "BRIGHT", style: "minimal" },
      { id: "s2-moody", label: "MOODY", style: "industrial" },
      { id: "s2-playful", label: "PLAYFUL", style: "maximalist" },
      { id: "s2-organized", label: "ORGANIZED", style: "minimal" },
      { id: "s2-collected", label: "COLLECTED", style: "maximalist" },
      { id: "s2-natural", label: "NATURAL", style: "organic" },
      { id: "s2-refined", label: "REFINED", style: "artisan" },
      { id: "s2-simple", label: "SIMPLE", style: "minimal" },
      { id: "s2-soft", label: "SOFT", style: "organic" },
      { id: "s2-textured", label: "TEXTURED", style: "artisan" },
      { id: "s2-clean", label: "CLEAN", style: "minimal" },
      { id: "s2-balanced", label: "BALANCED", style: "minimal" },
      { id: "s2-sanctuary", label: "SANCTUARY", style: "organic" },
      { id: "s2-quiet", label: "QUIET", style: "minimal" },
    ],
  },

  // Q3 — Morning Scene
  {
    id: "s3",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "image-grid",
    layout: "two-column-grid",
    bg: "#B09470",
    accent: "#1a1714",
    question: "YOUR MORNING SCENE",
    subtext: "Which space are you waking up in?",
    autoAdvance: true,
    imageOptions: [
      {
        id: "s3a",
        label: "THE LIGHT BATH",
        sublabel:
          "Soft light through linen curtains. White walls, natural wood, peaceful silence.",
        imageSrc: styleExplorerGridImage(6),
        unsplashQuery: "minimal bedroom morning light linen curtains",
        style: "minimal",
      },
      {
        id: "s3b",
        label: "THE WARM EMBRACE",
        sublabel:
          "Rich textures, warm colors. Books, candles, a soft throw waiting for you.",
        imageSrc: styleExplorerGridImage(7),
        unsplashQuery: "cozy warm bedroom rich textures books candles",
        style: "maximalist",
      },
      {
        id: "s3c",
        label: "THE GREEN RETREAT",
        sublabel:
          "Plants everywhere. Fresh air, natural light, life growing around you.",
        imageSrc: styleExplorerGridImage(8),
        unsplashQuery: "bedroom plants natural light indoor garden",
        style: "organic",
      },
      {
        id: "s3d",
        label: "THE QUIET STUDY",
        sublabel:
          "Dark wood, leather, brass. A space that feels serious and grounding.",
        imageSrc: styleExplorerGridImage(9),
        unsplashQuery: "dark wood leather study room bedroom moody",
        style: "industrial",
      },
    ],
  },

  // Q4 — Quick Fire
  {
    id: "s4",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "binary-pairs",
    layout: "vertical-split",
    bg: "#8A9E9A",
    accent: "#1a1714",
    question: "QUICK FIRE",
    subtext: "No thinking. Just instinct.",
    binaryPairs: [
      { id: "p1", left: "SUNRISE", right: "SUNSET" },
      { id: "p2", left: "MOUNTAINS", right: "OCEAN" },
      { id: "p3", left: "CANDLES", right: "BRIGHT LIGHTS" },
      { id: "p4", left: "OLD BOOKSTORE", right: "MODERN GALLERY" },
      { id: "p5", left: "COFFEE", right: "TEA" },
      { id: "p6", left: "ONE STATEMENT PIECE", right: "MANY SMALL DETAILS" },
      { id: "p7", left: "STRAIGHT LINES", right: "SOFT CURVES" },
      { id: "p8", left: "SILENCE", right: "BACKGROUND MUSIC" },
    ],
  },

  // Q5 — Color Feeling
  {
    id: "s5",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "palette-cards",
    layout: "offset-composition",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "COLOR FEELING",
    subtext: "Which palette lives in your head?",
    autoAdvance: true,
    paletteCards: [
      {
        id: "s5-whisper",
        name: "WHISPER",
        swatches: ["#FAF7F5", "#E8E0DA", "#D4C5B9", "#B8A99A", "#9C8E82"],
        style: "minimal",
      },
      {
        id: "s5-earth",
        name: "EARTH",
        swatches: ["#F2E8DF", "#D4A574", "#8B6F47", "#5C4033", "#3B2820"],
        style: "organic",
      },
      {
        id: "s5-ocean",
        name: "OCEAN",
        swatches: ["#EDF4F7", "#B8D4E3", "#6BA3BE", "#2E7D9B", "#1A4F6E"],
        style: "minimal",
      },
      {
        id: "s5-forest",
        name: "FOREST",
        swatches: ["#EFF5ED", "#B8D4A8", "#6B9B5E", "#3D6B35", "#2A4A25"],
        style: "organic",
      },
      {
        id: "s5-dusk",
        name: "DUSK",
        swatches: ["#F0EBF4", "#C9B8D9", "#9B7FBD", "#6D4F8A", "#4A2D6B"],
        style: "maximalist",
      },
      {
        id: "s5-blush",
        name: "BLUSH",
        swatches: ["#FDF2F0", "#F0D0CA", "#D4A09A", "#B87070", "#8C4A4A"],
        style: "artisan",
      },
      {
        id: "s5-storm",
        name: "STORM",
        swatches: ["#F0F0F2", "#B8B8C0", "#7A7A88", "#4A4A58", "#2D2D3B"],
        style: "industrial",
      },
      {
        id: "s5-desert",
        name: "DESERT",
        swatches: ["#F7F0E6", "#E8D4B0", "#C4A870", "#9B7D3E", "#6B5525"],
        style: "artisan",
      },
    ],
  },

  // Q6 — Texture Touch
  {
    id: "s6",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "multi-select",
    layout: "ghost-type",
    bg: "#B33D0E",
    accent: "#DDD5C4",
    question: "TEXTURE TOUCH",
    subtext: "Pick 3 materials you want to live with.",
    minSelect: 3,
    maxSelect: 3,
    options: [
      { id: "s6-lw", label: "LIGHT WOOD", style: "minimal" },
      { id: "s6-dw", label: "DARK WOOD", style: "industrial" },
      { id: "s6-mb", label: "MARBLE", style: "minimal" },
      { id: "s6-co", label: "CONCRETE", style: "industrial" },
      { id: "s6-li", label: "LINEN", style: "organic" },
      { id: "s6-ve", label: "VELVET", style: "maximalist" },
      { id: "s6-le", label: "LEATHER", style: "industrial" },
      { id: "s6-ra", label: "RATTAN", style: "organic" },
      { id: "s6-br", label: "BRASS", style: "artisan" },
      { id: "s6-bo", label: "BOUCLÉ", style: "organic" },
    ],
  },

  // Q7 — Furniture Style
  {
    id: "s7",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "sliders",
    layout: "editorial-stack",
    bg: "#6B7355",
    accent: "#DDD5C4",
    question: "FURNITURE STYLE",
    subtext: "Dial in your preferences.",
    sliders: [
      {
        id: "sofa",
        label: "SOFA",
        leftLabel: "COMPACT & CLEAN",
        rightLabel: "SCULPTURAL & BOLD",
      },
      {
        id: "table",
        label: "COFFEE TABLE",
        leftLabel: "GLASS & LIGHT",
        rightLabel: "SOLID & GROUNDED",
      },
      {
        id: "lighting",
        label: "LIGHTING",
        leftLabel: "MINIMAL & HIDDEN",
        rightLabel: "STATEMENT PIECE",
      },
      {
        id: "storage",
        label: "STORAGE",
        leftLabel: "CLOSED & SEAMLESS",
        rightLabel: "OPEN & DISPLAYED",
      },
      {
        id: "dining",
        label: "DINING",
        leftLabel: "SIMPLE & LIGHT",
        rightLabel: "SUBSTANTIAL & FORMAL",
      },
    ],
  },

  // Q8 — Life Reality
  {
    id: "s8",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "life-reality",
    layout: "full-color-split",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "LIFE REALITY",
    subtext: "Tell us about your actual home life.",
    lifeRealityGroups: [
      {
        id: "org",
        label: "ORGANISATION",
        options: [
          { id: "org-a", label: "EVERYTHING HAS ITS PLACE" },
          { id: "org-b", label: "MOSTLY TIDY, CHAOS CORNERS" },
          { id: "org-c", label: "CREATIVE MESS, DON'T JUDGE" },
        ],
      },
      {
        id: "hh",
        label: "HOUSEHOLD",
        options: [
          { id: "hh-a", label: "NO KIDS OR PETS" },
          { id: "hh-b", label: "PETS" },
          { id: "hh-c", label: "KIDS" },
          { id: "hh-d", label: "BOTH" },
        ],
      },
      {
        id: "plants",
        label: "PLANTS",
        options: [
          { id: "pl-a", label: "YES, GREEN THUMB" },
          { id: "pl-b", label: "SOMETIMES" },
          { id: "pl-c", label: "THEY FEAR ME" },
        ],
      },
    ],
  },

  // Q9 — Space Struggles
  {
    id: "s9",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "multi-select",
    layout: "hover-reactive",
    bg: "#B09470",
    accent: "#1a1714",
    question: "SPACE STRUGGLES",
    subtext: "Optional. Pick anything that resonates.",
    optional: true,
    options: [
      { id: "s9a", label: "FEELS CLUTTERED EVEN WHEN IT'S CLEAN" },
      { id: "s9b", label: "CAN'T RELAX OR SWITCH OFF" },
      { id: "s9c", label: "LIGHTING ALWAYS FEELS OFF" },
      { id: "s9d", label: "WORKING FROM HOME IS HARD" },
      { id: "s9e", label: "I SLEEP POORLY" },
      { id: "s9f", label: "NOTHING SEEMS TO MATCH OR GO TOGETHER" },
      { id: "s9g", label: "SPACE FEELS COLD OR STERILE" },
      { id: "s9h", label: "ROOM FEELS TOO SMALL FOR WHAT I NEED" },
      { id: "s9i", label: "I JUST DON'T KNOW WHERE TO START" },
    ],
  },

  // Q10 — Wellness Goal
  {
    id: "s10",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "single-select",
    layout: "giant-type-small-options",
    bg: "#8A9E9A",
    accent: "#1a1714",
    question: "WELLNESS GOAL",
    subtext: "What should your space do for you?",
    autoAdvance: true,
    options: [
      { id: "s10a", label: "BETTER SLEEP", style: "organic" },
      { id: "s10b", label: "A CALM MIND", style: "minimal" },
      { id: "s10c", label: "MORE FOCUS", style: "industrial" },
      { id: "s10d", label: "ENERGY & MOTIVATION", style: "maximalist" },
    ],
  },

  // Q11 — Dealbreakers
  {
    id: "s11",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "multi-select",
    layout: "scattered-chips",
    bg: "#1a1714",
    accent: "#DDD5C4",
    question: "DEALBREAKERS",
    subtext: "Toggle anything you'd never live with.",
    optional: true,
    options: [
      { id: "s11a", label: "SUPER RUSTIC WOOD EVERYWHERE" },
      { id: "s11b", label: "HEAVY GREY ON GREY" },
      { id: "s11c", label: "BLACK METAL INDUSTRIAL EVERYTHING" },
      { id: "s11d", label: "ORNATE TRADITIONAL DETAILS" },
      { id: "s11e", label: "NEON ACCENTS" },
      { id: "s11f", label: "MAXIMALIST CLUTTER" },
      { id: "s11g", label: "STERILE HOTEL ROOM FEEL" },
      { id: "s11h", label: "EVERYTHING MATCHING TOO PERFECTLY" },
      { id: "s11i", label: "TOO TRENDY, WILL LOOK DATED IN 2 YEARS" },
    ],
  },

  // Q12 — Dream Room
  {
    id: "s12",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "image-grid",
    layout: "two-column-grid",
    bg: "#DDD5C4",
    accent: "#B33D0E",
    question: "DREAM ROOM",
    subtext: "One space. The one.",
    autoAdvance: true,
    imageOptions: [
      {
        id: "s12a",
        label: "WARM MINIMALIST",
        sublabel: "Clean lines, natural materials, sunlight",
        imageSrc: styleExplorerGridImage(10),
        unsplashQuery: "warm minimalist living room natural light wood",
        style: "minimal",
      },
      {
        id: "s12b",
        label: "COZY COLLECTED",
        sublabel: "Layered textures, books, warm lighting",
        imageSrc: styleExplorerGridImage(11),
        unsplashQuery: "cozy collected living room books layered textures",
        style: "maximalist",
      },
      {
        id: "s12c",
        label: "LIGHT AIRY",
        sublabel: "Whites, plants, breathing room",
        imageSrc: styleExplorerGridImage(12),
        unsplashQuery: "light airy white living room plants scandinavian",
        style: "organic",
      },
      {
        id: "s12d",
        label: "BOLD CHARACTER",
        sublabel: "Dark accents, statement furniture, drama",
        imageSrc: styleExplorerGridImage(13),
        unsplashQuery:
          "bold dark interior living room statement furniture dramatic",
        style: "industrial",
      },
    ],
  },

  // Q13 — Inspiration Sources
  {
    id: "s13",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "multi-select",
    layout: "ghost-type",
    bg: "#6B7355",
    accent: "#DDD5C4",
    question: "INSPIRATION SOURCES",
    subtext: "Optional. Where do you discover spaces you love?",
    optional: true,
    options: [
      { id: "s13a", label: "PINTEREST BOARDS" },
      { id: "s13b", label: "INSTAGRAM / TIKTOK" },
      { id: "s13c", label: "DESIGN MAGAZINES" },
      { id: "s13d", label: "HOTELS & AIRBNBS" },
      { id: "s13e", label: "FRIENDS' HOMES" },
      { id: "s13f", label: "SHOWROOMS & STORES" },
      { id: "s13g", label: "I DON'T REALLY LOOK. THAT'S WHY I'M HERE" },
    ],
  },

  // Q14 — Free Text
  {
    id: "s14",
    flow: "style",
    section: "STYLE DISCOVERY",
    type: "free-text",
    layout: "full-bleed-statement",
    bg: "#B09470",
    accent: "#1a1714",
    question: "IN YOUR OWN WORDS",
    subtext: "Describe your ideal space. No wrong answers.",
    optional: true,
    placeholders: [
      "light and airy, soft edges, cozy",
      "feels like a boutique hotel but warmer",
      "earthy calm with one wow piece",
      "organized, everything has its place, quiet",
    ],
  },
];
