"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { displayConversationTitle } from "@/lib/conversations/conversation-title";
import type { ChatSecKey } from "./chat-workspace-context";

type RecentConversation = {
  id: string;
  title: string;
  messageCount?: number;
};

type ChatSectionViewProps = {
  section: ChatSecKey;
  confirmedPreferences: Record<string, string | null>;
  recents: RecentConversation[];
  messageCount: number;
  currentConversationId: string;
  onExit: () => void;
  onOpenSection: (key: ChatSecKey) => void;
  onOpenConversation: (id: string) => void;
  onAsk: (prompt: string) => void;
  onToast: (message: string) => void;
};

type FileItem = {
  name: string;
  category: "Documents" | "Floorplans" | "Images";
  meta: string;
  description: string;
};

const SECTION_COPY: Record<ChatSecKey, { title: string; sub: string }> = {
  project: {
    title: "Projects",
    sub: "Everything living under “Bedroom refresh”.",
  },
  files: {
    title: "Artifacts",
    sub: "All artifacts from chats in your active project.",
  },
  discover: {
    title: "Insights",
    sub: "What Eva has locked from your chats, what’s still missing, and pieces worth weighing.",
  },
  plan: {
    title: "Room plan",
    sub: "Core pieces, budget remaining, and orderable readiness.",
  },
};

const TASKS = [
  [
    "Confirm the room preferences with Eva",
    "conversation",
    "in progress · high",
  ],
  ["Approve one moodboard direction", "review", "queued · medium"],
  ["Pick a delivery week for the console", "orders", "queued · low"],
] as const;

/** Preference rows in Insights — mirrors the chat preference rail. */
const INSIGHT_PREFS: Record<
  string,
  {
    label: string;
    openHint: string;
    askPrompt: string;
    reviewPrompt: (value: string) => string;
  }
> = {
  room: {
    label: "Room",
    openHint: "Which space are we designing?",
    askPrompt:
      "Help me choose which room to design first, and what matters most about that space.",
    reviewPrompt: (value) =>
      `Review my room direction (${value}). Flag anything important we’re still missing.`,
  },
  budget: {
    label: "Budget",
    openHint: "No spend range yet",
    askPrompt:
      "Help me set a realistic budget for this project — overall cap and where to save vs splurge.",
    reviewPrompt: (value) =>
      `Review my budget (${value}). Does it fit the room and furniture needs we’ve discussed?`,
  },
  style: {
    label: "Style",
    openHint: "Look and mood still open",
    askPrompt:
      "Help me name a clear design style for this project — references, mood, and what to avoid.",
    reviewPrompt: (value) =>
      `Review my style direction (${value}). Keep what’s strong and tighten anything vague.`,
  },
  color: {
    label: "Palette",
    openHint: "No colors locked yet",
    askPrompt:
      "Help me build a color palette for this room — base, accent, and materials that carry it.",
    reviewPrompt: (value) =>
      `Review my palette (${value}). Suggest refinements that stay cohesive with the style.`,
  },
  furniture: {
    label: "Furniture",
    openHint: "Needs list is empty",
    askPrompt:
      "Help me list the furniture this room actually needs, prioritized from must-have to nice-to-have.",
    reviewPrompt: (value) =>
      `Review my furniture needs (${value}). What’s essential, and what can wait?`,
  },
};

const FILES: FileItem[] = [
  {
    name: "floorplan-v2.png",
    category: "Floorplans",
    meta: "1.2 MB · uploaded 2d ago",
    description:
      "Scaled plan of the 68m² flat with the new sofa footprint marked.",
  },
  {
    name: "moodboard-warm.pdf",
    category: "Documents",
    meta: "3.4 MB · generated by Eva",
    description: "Nine-frame warm-minimal direction with clay accents.",
  },
  {
    name: "summary-v1.md",
    category: "Documents",
    meta: "2 KB · exported 5d ago",
    description: "First export of the project summary.",
  },
];

const RECOMMENDATIONS = [
  ["Low oak console", "S$680", "Storage", "Warm wood · keeps sightlines clear"],
  ["Clay flatweave rug", "S$520", "Rug", "Soft ground for a calm palette"],
  [
    "Arc floor lamp, brushed brass",
    "S$420",
    "Lighting",
    "Evening pool of ambient light",
  ],
  [
    "Deep-seat modular sofa",
    "S$2,180",
    "Sofa",
    "Lounge-first · easy to reconfigure",
  ],
] as const;

function pressKey(
  event: React.KeyboardEvent<HTMLElement>,
  onClick: () => void,
) {
  if (event.key === "Enter" || event.key === " ") {
    event.preventDefault();
    onClick();
  }
}

/** Prototype uses span/div for chrome (not <button>) so Windows UA can’t paint cool grey-blue fills. */
function Action({
  children,
  onClick,
  dataAttr,
}: {
  children: React.ReactNode;
  onClick: () => void;
  dataAttr?: Record<string, string>;
}) {
  return (
    <span
      role="button"
      tabIndex={0}
      className="wf-exbtn"
      onClick={onClick}
      onKeyDown={(event) => pressKey(event, onClick)}
      {...dataAttr}
    >
      {children}
    </span>
  );
}

function Check({
  checked,
  onClick,
  dataAttr,
}: {
  checked: boolean;
  onClick: () => void;
  dataAttr: Record<string, string>;
}) {
  return (
    <span
      role="button"
      tabIndex={0}
      className={`wf-ck${checked ? " on" : ""}`}
      aria-pressed={checked}
      onClick={onClick}
      onKeyDown={(event) => pressKey(event, onClick)}
      {...dataAttr}
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="3"
      >
        <path d="M20 6 9 17l-5-5" />
      </svg>
    </span>
  );
}

function FileIcon({ category }: { category: FileItem["category"] }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
    >
      {category === "Floorplans" ? (
        <>
          <rect width="18" height="18" x="3" y="3" rx="2" />
          <path d="M3 12h7v9M10 12V3M14 8h7" />
        </>
      ) : category === "Images" ? (
        <>
          <rect width="18" height="18" x="3" y="3" rx="2" />
          <circle cx="9" cy="9" r="2" />
          <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
        </>
      ) : (
        <>
          <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
          <path d="M14 2v4a2 2 0 0 0 2 2h4" />
        </>
      )}
    </svg>
  );
}

export function ChatSectionView(props: ChatSectionViewProps) {
  const copy = SECTION_COPY[props.section];
  const [tasks, setTasks] = useState<Record<number, boolean>>({});
  const [shortlist, setShortlist] = useState<Record<string, boolean>>({});
  const [fileCategory, setFileCategory] = useState("All");
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const previousSection = useRef(props.section);

  useEffect(() => {
    if (props.section === "files" && previousSection.current !== "files") {
      setFileCategory("All");
      setSelectedFile(null);
    }
    previousSection.current = props.section;
  }, [props.section]);

  useEffect(() => {
    if (props.section !== "files" || !selectedFile) return;
    function onKey(event: KeyboardEvent) {
      if (event.key !== "Escape") return;
      event.stopPropagation();
      setSelectedFile(null);
    }
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [props.section, selectedFile]);

  function ask(prompt: string) {
    props.onExit();
    props.onAsk(prompt);
  }

  function toggleShortlist(name: string) {
    setShortlist((current) => {
      const added = !current[name];
      props.onToast(
        added ? "Saved to your shortlist" : "Removed from shortlist",
      );
      return { ...current, [name]: added };
    });
  }

  return (
    <div className="wf-secv wf-viewin">
      <h1 className="wf-secv__h">{copy.title}</h1>
      <p className="wf-secv__sub">{copy.sub}</p>
      {props.section === "project" ? (
        <ProjectSection
          {...props}
          tasks={tasks}
          shortlist={shortlist}
          onToggleTask={(index) =>
            setTasks((current) => ({ ...current, [index]: !current[index] }))
          }
          onToggleShortlist={toggleShortlist}
        />
      ) : null}
      {props.section === "files" ? (
        <FilesSection
          selectedFile={selectedFile}
          category={fileCategory}
          onSelectFile={setSelectedFile}
          onSelectCategory={setFileCategory}
          onAsk={ask}
          onToast={props.onToast}
        />
      ) : null}
      {props.section === "discover" ? (
        <DiscoverSection
          preferences={props.confirmedPreferences}
          shortlist={shortlist}
          onToggleShortlist={toggleShortlist}
          onAsk={ask}
        />
      ) : null}
      {props.section === "plan" ? <RoomPlanSection onAsk={ask} /> : null}
    </div>
  );
}

function ProjectSection({
  recents,
  currentConversationId,
  messageCount,
  tasks,
  shortlist,
  onExit,
  onOpenSection,
  onOpenConversation,
  onToast,
  onToggleTask,
  onToggleShortlist,
}: ChatSectionViewProps & {
  tasks: Record<number, boolean>;
  shortlist: Record<string, boolean>;
  onToggleTask: (index: number) => void;
  onToggleShortlist: (name: string) => void;
}) {
  const shortlisted = Object.keys(shortlist).filter((name) => shortlist[name]);
  return (
    <>
      <div className="wf-scard">
        <p className="wf-scard__t">
          Bedroom refresh<span className="wf-schip terra">Active</span>
        </p>
        <p className="wf-scard__d">
          Shared with Ana K. and Studio Eva · started 3 weeks ago.
        </p>
        <div className="wf-scard__act">
          <Action onClick={onExit} dataAttr={{ "data-sec-back": "" }}>
            Open project chat
          </Action>
          <Action
            onClick={() => onToast("Team review is out of wireframe scope")}
            dataAttr={{
              "data-sec-toast": "Team review is out of wireframe scope",
            }}
          >
            Team review &amp; timeline
          </Action>
          <Action
            onClick={() => onToast("Invite link copied (demo)")}
            dataAttr={{ "data-sec-toast": "Invite link copied (demo)" }}
          >
            Invite (demo)
          </Action>
        </div>
      </div>
      <p className="wf-sec__lbl">Tasks</p>
      {TASKS.map((task, index) => (
        <div className="wf-srow" key={task[0]}>
          <Check
            checked={!!tasks[index]}
            onClick={() => onToggleTask(index)}
            dataAttr={{ "data-task": String(index) }}
          />
          <span className="wf-srow__b">
            <span
              className="wf-srow__t"
              style={
                tasks[index]
                  ? { textDecoration: "line-through", opacity: 0.6 }
                  : undefined
              }
            >
              {task[0]}
            </span>
            <span className="wf-srow__m">{task[1]}</span>
          </span>
          <span className="wf-tstat">{task[2]}</span>
        </div>
      ))}
      <p className="wf-sec__lbl">Shortlist</p>
      {shortlisted.length ? (
        shortlisted.map((name) => (
          <div className="wf-srow" key={name}>
            <span className="wf-srow__b">
              <span className="wf-srow__t">{name}</span>
              <span className="wf-srow__m">saved from recommendations</span>
            </span>
            <Action onClick={() => onToggleShortlist(name)}>Remove</Action>
          </div>
        ))
      ) : (
        <p className="wf-scard__d">
          Nothing shortlisted yet, pick pieces in{" "}
          <span
            role="button"
            tabIndex={0}
            className="wf-alink"
            data-sec-open="discover"
            onClick={() => onOpenSection("discover")}
            onKeyDown={(event) =>
              pressKey(event, () => onOpenSection("discover"))
            }
          >
            Insights
          </span>
          .
        </p>
      )}
      <p className="wf-sec__lbl">Conversations in this project</p>
      {recents.length ? (
        recents.map((conversation) => (
          <div className="wf-srow" key={conversation.id}>
            <svg
              className="wf-srow__i"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
            >
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
            </svg>
            <span className="wf-srow__b">
              <span className="wf-srow__t">
                {displayConversationTitle(
                  conversation.title,
                  conversation.title,
                )}
              </span>
              <span className="wf-srow__m">
                {conversation.messageCount ??
                  (conversation.id === currentConversationId
                    ? messageCount
                    : "Recent")}{" "}
                {conversation.messageCount !== undefined ||
                conversation.id === currentConversationId
                  ? "messages"
                  : "conversation"}
              </span>
            </span>
            <Action
              onClick={() => onOpenConversation(conversation.id)}
              dataAttr={{ "data-sec-sess": conversation.id }}
            >
              Open
            </Action>
          </div>
        ))
      ) : (
        <p className="wf-scard__d">No conversations yet.</p>
      )}
      <div className="wf-scard" style={{ marginTop: 9 }}>
        <p className="wf-scard__d">
          Track core pieces and remaining budget in your room plan.
        </p>
        <div className="wf-scard__act">
          <Action
            onClick={() => onOpenSection("plan")}
            dataAttr={{ "data-sec-open": "plan" }}
          >
            Open room plan
          </Action>
        </div>
      </div>
    </>
  );
}

function FilesSection({
  selectedFile,
  category,
  onSelectFile,
  onSelectCategory,
  onAsk,
  onToast,
}: {
  selectedFile: string | null;
  category: string;
  onSelectFile: (name: string | null) => void;
  onSelectCategory: (category: string) => void;
  onAsk: (prompt: string) => void;
  onToast: (message: string) => void;
}) {
  const selected = FILES.find((file) => file.name === selectedFile);
  const visible = FILES.filter(
    (file) => category === "All" || file.category === category,
  );
  const cards = (files: FileItem[]) =>
    files.map((file) => (
      <div
        role="button"
        tabIndex={0}
        className={`wf-fcard${selectedFile === file.name ? " on" : ""}`}
        data-fcat={file.category}
        data-file-open={file.name}
        onClick={() => onSelectFile(file.name)}
        onKeyDown={(event) => pressKey(event, () => onSelectFile(file.name))}
        key={file.name}
      >
        <div className={`wf-fthumb k-${file.category}`}>
          <FileIcon category={file.category} />
        </div>
        <div className="wf-fcard__b">
          <span className="wf-srow__t" style={{ display: "block" }}>
            {file.name}
          </span>
          <span className="wf-srow__m">
            {file.category} · {file.meta}
          </span>
        </div>
      </div>
    ));

  if (selected) {
    return (
      <div className="wf-fsplit">
        <div className="wf-fsplit__list">
          <div className="wf-fgrid" data-file-list>
            {cards(FILES)}
          </div>
        </div>
        <div className="wf-fsplit__det">
          <div className="wf-fdet__hero">
            <FileIcon category={selected.category} />
          </div>
          <p className="wf-scard__t" style={{ fontSize: 17 }}>
            {selected.name}
          </p>
          <p className="wf-scard__d">{selected.description}</p>
          <div className="wf-scard__act" style={{ marginTop: 10 }}>
            <span className="wf-kchip">{selected.category}</span>
            <span className="wf-kchip">{selected.meta}</span>
          </div>
          <div className="wf-scard__act" style={{ marginTop: 14 }}>
            <Action
              onClick={() => onToast("Download started (demo)")}
              dataAttr={{ "data-sec-toast": "Download started (demo)" }}
            >
              ↓ Download
            </Action>
            <Action
              onClick={() => onAsk(`What should I do with ${selected.name}?`)}
              dataAttr={{
                "data-sec-chat": `What should I do with ${selected.name}?`,
              }}
            >
              Ask Eva about this file
            </Action>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="wf-sfilter">
        {["All", "Documents", "Floorplans", "Images"].map((item) => (
          <span
            role="button"
            tabIndex={0}
            className={`wf-chip2${category === item ? " is-active" : ""}`}
            data-file-cat={item}
            onClick={() => onSelectCategory(item)}
            onKeyDown={(event) => pressKey(event, () => onSelectCategory(item))}
            key={item}
          >
            {item}
          </span>
        ))}
      </div>
      <div className="wf-fgrid" data-file-list>
        {cards(visible)}
      </div>
    </>
  );
}

function DiscoverSection({
  preferences,
  shortlist,
  onToggleShortlist,
  onAsk,
}: {
  preferences: Record<string, string | null>;
  shortlist: Record<string, boolean>;
  onToggleShortlist: (name: string) => void;
  onAsk: (prompt: string) => void;
}) {
  const settled = useMemo(
    () =>
      Object.entries(INSIGHT_PREFS)
        .map(([key, meta]) => {
          const value = preferences[key]?.trim();
          return value ? ([key, meta, value] as const) : null;
        })
        .filter(
          (
            row,
          ): row is readonly [string, (typeof INSIGHT_PREFS)[string], string] =>
            Boolean(row),
        ),
    [preferences],
  );
  const open = useMemo(
    () =>
      Object.entries(INSIGHT_PREFS)
        .filter(([key]) => !preferences[key]?.trim())
        .map(([key, meta]) => [key, meta] as const),
    [preferences],
  );

  return (
    <>
      <p className="wf-sec__lbl">Locked in</p>
      {settled.length ? (
        settled.map(([key, meta, value]) => (
          <div className="wf-srow" key={key}>
            <span className="wf-srow__b">
              <span className="wf-srow__t">{meta.label}</span>
              <span className="wf-srow__m">{value}</span>
            </span>
            <Action
              onClick={() => onAsk(meta.reviewPrompt(value))}
              dataAttr={{
                "data-sec-chat": meta.reviewPrompt(value),
              }}
            >
              Refine
            </Action>
          </div>
        ))
      ) : (
        <p className="wf-scard__d">
          Nothing locked yet. Tell Eva in chat, or edit the preference panel —
          Insights stays in sync with what you confirm.
        </p>
      )}

      {open.length ? (
        <>
          <p className="wf-sec__lbl">Still to decide</p>
          {open.map(([key, meta]) => (
            <div className="wf-srow" key={key}>
              <span className="wf-srow__b">
                <span className="wf-srow__t">{meta.label}</span>
                <span className="wf-srow__m">{meta.openHint}</span>
              </span>
              <Action
                onClick={() => onAsk(meta.askPrompt)}
                dataAttr={{
                  "data-sec-chat": meta.askPrompt,
                }}
              >
                Ask Eva
              </Action>
            </div>
          ))}
        </>
      ) : null}

      <p className="wf-sec__lbl">
        Worth reviewing
        <span className="wf-lblhint">suggested next — save what fits</span>
      </p>
      <RecommendationsSection
        shortlist={shortlist}
        onToggleShortlist={onToggleShortlist}
        onAsk={onAsk}
      />
    </>
  );
}

function RecommendationsSection({
  shortlist,
  onToggleShortlist,
  onAsk,
}: {
  shortlist: Record<string, boolean>;
  onToggleShortlist: (name: string) => void;
  onAsk: (prompt: string) => void;
}) {
  return (
    <>
      {RECOMMENDATIONS.map((item) => (
        <div className="wf-srow" key={item[0]}>
          <span className="wf-srow__b">
            <span className="wf-srow__t">{item[0]}</span>
            <span className="wf-srow__m">
              {item[2]} · {item[3]} · {item[1]}
            </span>
          </span>
          <span
            role="button"
            tabIndex={0}
            className={`wf-slbtn${shortlist[item[0]] ? " on" : ""}`}
            data-sl={item[0]}
            onClick={() => onToggleShortlist(item[0])}
            onKeyDown={(event) =>
              pressKey(event, () => onToggleShortlist(item[0]))
            }
          >
            {shortlist[item[0]] ? "Saved" : "Save"}
          </span>
          <Action
            onClick={() =>
              onAsk(
                `Would the ${item[0]} (${item[2]}, ${item[1]}) fit this project? Pros, cons, and what to pair it with.`,
              )
            }
            dataAttr={{
              "data-sec-chat": `Would the ${item[0]} (${item[2]}, ${item[1]}) fit this project? Pros, cons, and what to pair it with.`,
            }}
          >
            Compare
          </Action>
        </div>
      ))}
    </>
  );
}

type RoomPlanApi = {
  id: string;
  name: string;
  currency: string;
  budgetCapCents: number | null;
  remainingBudgetCents: number | null;
  readiness: {
    score: number;
    label: string;
    missingCore: string[];
    overBudget: boolean;
  };
  orderCtaEnabled: boolean;
  items: Array<{
    id: string;
    label: string;
    priority: string;
    status: string;
    budgetCents: number | null;
  }>;
};

function formatCents(cents: number | null, currency: string): string {
  if (cents == null) return "—";
  const code = currency.trim().toUpperCase() || "SGD";
  if (code === "SGD") {
    return `S$${Math.round(cents / 100).toLocaleString("en-SG")}`;
  }
  try {
    return new Intl.NumberFormat("en-SG", {
      style: "currency",
      currency: code,
      maximumFractionDigits: 0,
    }).format(cents / 100);
  } catch {
    return `${code} ${(cents / 100).toFixed(0)}`;
  }
}

function RoomPlanSection({ onAsk }: { onAsk: (prompt: string) => void }) {
  const [plans, setPlans] = useState<RoomPlanApi[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch("/api/account/room-plans");
        if (response.status === 503) {
          if (!cancelled) {
            setPlans([]);
            setError("Room plans are turned off.");
          }
          return;
        }
        if (!response.ok) {
          throw new Error("Failed to load room plans.");
        }
        const payload = (await response.json()) as { plans?: RoomPlanApi[] };
        if (!cancelled) setPlans(payload.plans ?? []);
      } catch {
        if (!cancelled) setError("Could not load room plans.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return <p className="wf-scard__d">Loading room plan…</p>;
  }
  if (error) {
    return <p className="wf-scard__d">{error}</p>;
  }
  if (!plans.length) {
    return (
      <p className="wf-scard__d">
        No room plan yet. Ask Eva to start one, or save recommendations into a
        plan when the feature flag is on.
      </p>
    );
  }

  const plan = plans[0]!;
  const cap = plan.budgetCapCents ?? 0;
  const remaining = plan.remainingBudgetCents ?? 0;
  const spent = Math.max(0, cap - remaining);
  const fillPct = cap > 0 ? Math.min(100, Math.round((spent / cap) * 100)) : 0;

  return (
    <>
      <div className="wf-srow">
        <span className="wf-srow__b">
          <span className="wf-srow__t">{plan.name}</span>
          <span className="wf-srow__m">
            {plan.readiness.label} · score {plan.readiness.score}
            {plan.readiness.overBudget ? " · over budget" : ""}
          </span>
        </span>
        <span
          className="wf-rthumb"
          aria-label={`Readiness ${plan.readiness.score}`}
          style={{
            display: "grid",
            placeItems: "center",
            fontSize: 12,
            fontWeight: 600,
          }}
        >
          {plan.readiness.score}
        </span>
      </div>

      <p className="wf-sec__lbl">Budget</p>
      <div className="wf-bdl">
        <div className="wf-bdrow">
          <span>Cap</span>
          <b>{formatCents(plan.budgetCapCents, plan.currency)}</b>
        </div>
        <div className="wf-bdrow">
          <span>Remaining</span>
          <b>{formatCents(plan.remainingBudgetCents, plan.currency)}</b>
        </div>
        <div
          className="wf-bdrow"
          style={{
            height: 8,
            padding: 0,
            marginTop: 8,
            background: "color-mix(in srgb, currentColor 12%, transparent)",
            borderRadius: 999,
            overflow: "hidden",
          }}
        >
          <div
            style={{
              width: `${fillPct}%`,
              height: "100%",
              background: "currentColor",
              opacity: 0.55,
            }}
          />
        </div>
      </div>

      <p className="wf-sec__lbl">Items</p>
      {plan.items.map((item) => (
        <div className="wf-srow" key={item.id}>
          <span className="wf-srow__b">
            <span className="wf-srow__t">
              {item.label}
              <span className="wf-srow__m" style={{ marginLeft: 8 }}>
                {item.priority} · {item.status}
              </span>
            </span>
            <span className="wf-srow__m">
              {formatCents(item.budgetCents, plan.currency)}
            </span>
          </span>
          <Action
            onClick={() =>
              onAsk(
                `Help me decide on the ${item.label} for my room plan. Remaining budget is ${formatCents(plan.remainingBudgetCents, plan.currency)}.`,
              )
            }
          >
            Ask Eva
          </Action>
        </div>
      ))}

      {plan.readiness.missingCore.length ? (
        <>
          <p className="wf-sec__lbl">Missing core</p>
          {plan.readiness.missingCore.map((label) => (
            <div className="wf-srow" key={label}>
              <span className="wf-srow__b">
                <span className="wf-srow__t">{label}</span>
                <span className="wf-srow__m">
                  still needed before ready to order
                </span>
              </span>
            </div>
          ))}
        </>
      ) : null}

      {plan.readiness.label === "ready to order" ? (
        <p className="wf-scard__d">
          {plan.orderCtaEnabled
            ? "Ready to order — checkout coming soon"
            : "Ready to order — checkout coming soon"}
        </p>
      ) : null}
    </>
  );
}
