"use client";

import { useStore } from "@studio/store";
import { CloseIcon } from "@studio/icons";
import type { AssetGeneration } from "@studio/store/generations-slice";
import { placeGeneratedAssetIntoScene } from "@studio/scene/place-generated-asset";

/**
 * Recent Generations bar — horizontal strip of tiles above the chat
 * dock. Shows two flavors of past work:
 *
 *   1. Arrange runs (from /api/arrange — the F2 planner pipeline).
 *      Click a tile → restoreFromHistory loads that run's candidates
 *      into OptionsTab/InspectTab, planner opens.
 *
 *   2. Asset generations (from /api/generate-asset — Turn 3 pipeline).
 *      Each is a single piece the user generated by typing in
 *      "Furniture" mode. Tile shows a thumbnail of the Flux 2D image
 *      plus a label. Click → drops the piece into the current scene
 *      at the apartment / room center; user drags to position via
 *      the existing translation gizmo.
 *
 * Self-gates: hidden when both arrays are empty AND when in immersive
 * mode (the user is reviewing a render, the bar would clutter).
 *
 * The visual layout is "Recent" label + arrange-run tiles + asset-
 * tiles in a single horizontal strip, scrollable horizontally if the
 * total width exceeds the viewport. Asset tiles are visually
 * distinct (image-thumb-led) from arrange tiles (text-led) so the
 * eye can sort them at a glance.
 */

const ACCENT = "#FF5A1F";
const INK = "#1A1A1A";
const UI_FONT = "var(--font-app), system-ui, sans-serif";

function relativeTime(ms: number): string {
  const sec = Math.max(0, Math.floor((Date.now() - ms) / 1000));
  if (sec < 30) return "just now";
  if (sec < 60) return `${sec}s ago`;
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const day = Math.floor(hr / 24);
  return `${day}d ago`;
}

export function RecentGenerationsBar() {
  // Arrange-history fields (existing).
  const history = useStore((s) => s.history);
  const candidates = useStore((s) => s.candidates);
  const restoreFromHistory = useStore((s) => s.restoreFromHistory);
  const removeFromHistory = useStore((s) => s.removeFromHistory);
  const setPlannerOpen = useStore((s) => s.setPlannerOpen);
  const immersive = useStore((s) => s.immersive);

  // Asset-generation fields (new).
  const assetGenerations = useStore((s) => s.assetGenerations);
  const removeAssetGeneration = useStore((s) => s.removeAssetGeneration);
  const apartmentCenter = useStore((s) => s.apartmentCenter);
  const sceneSource = useStore((s) => s.sceneSource);

  // Hide when nothing to show (or immersive mode).
  if (immersive || (history.length === 0 && assetGenerations.length === 0)) {
    return null;
  }

  // Find which arrange run (if any) matches the current candidate set.
  const activeId = history.find((h) => h.candidates === candidates)?.id;

  const handlePickRun = (runId: string) => {
    restoreFromHistory(runId);
    setPlannerOpen(true);
  };

  const handlePickAsset = (asset: AssetGeneration) => {
    placeGeneratedAssetIntoScene(asset, {
      apartmentCenter,
      sceneSource,
    });
    // No auto-select. The tile-click path is now used for
    // duplicating (auto-placement happens in chat-slice immediately
    // after generation). Auto-selecting put the orange wireframe +
    // selection circle on the new piece, which the user found
    // visually noisy on the blank canvas. They can click the piece
    // in the 3D scene if they want to drag it.
  };

  return (
    <div
      role="region"
      aria-label="Recent generations"
      style={{
        position: "fixed",
        bottom: 130, // sits just above the chat dock
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 5,
        display: "flex",
        gap: 8,
        padding: "8px 10px",
        background: "rgba(255, 251, 246, 0.92)",
        backdropFilter: "blur(6px)",
        border: "1px solid rgba(26, 26, 26, 0.08)",
        borderRadius: 14,
        boxShadow: "0 8px 24px rgba(26, 26, 26, 0.08)",
        maxWidth: "min(720px, calc(100vw - 32px))",
        overflowX: "auto",
      }}
    >
      <span
        style={{
          display: "inline-flex",
          alignItems: "center",
          padding: "0 8px 0 4px",
          fontSize: 10,
          fontWeight: 500,
          letterSpacing: "0.06em",
          textTransform: "uppercase",
          color: "rgba(26, 26, 26, 0.5)",
          flexShrink: 0,
        }}
      >
        Recent
      </span>

      {/* Asset-generation tiles first (they're newest workflow). */}
      {assetGenerations.map((asset) => (
        <AssetTile
          key={asset.id}
          asset={asset}
          onPick={handlePickAsset}
          onRemove={removeAssetGeneration}
        />
      ))}

      {/* Arrange-history tiles. */}
      {history.map((run, idx) => {
        const runNumber = history.length - idx;
        const isActive = run.id === activeId;
        return (
          <div
            key={run.id}
            role="group"
            style={{
              position: "relative",
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
              gap: 2,
              padding: "6px 22px 6px 10px",
              borderRadius: 10,
              background: isActive
                ? "rgba(255, 90, 31, 0.1)"
                : "rgba(26, 26, 26, 0.04)",
              border: isActive
                ? "1px solid rgba(255, 90, 31, 0.25)"
                : "1px solid transparent",
              flexShrink: 0,
            }}
          >
            <button
              type="button"
              onClick={() => handlePickRun(run.id)}
              title={`Restore Run ${runNumber} (${run.candidates.length} options)`}
              style={{
                background: "transparent",
                border: "none",
                padding: 0,
                cursor: "pointer",
                textAlign: "left",
                fontFamily: UI_FONT,
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "baseline",
                  gap: 6,
                  fontSize: 11,
                  fontWeight: 500,
                  color: isActive ? ACCENT : INK,
                }}
              >
                <span>Run {runNumber}</span>
                {run.applied && (
                  <span
                    aria-label="A candidate from this run was applied"
                    title="A candidate from this run was applied"
                    style={{
                      width: 6,
                      height: 6,
                      borderRadius: 999,
                      background: ACCENT,
                      display: "inline-block",
                    }}
                  />
                )}
              </div>
              <div
                style={{
                  fontSize: 10,
                  color: "rgba(26, 26, 26, 0.5)",
                  fontWeight: 500,
                  marginTop: 1,
                }}
              >
                {relativeTime(run.generatedAt)} · {run.candidates.length} option
                {run.candidates.length === 1 ? "" : "s"}
              </div>
            </button>
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                removeFromHistory(run.id);
              }}
              aria-label={`Remove Run ${runNumber} from history`}
              title="Remove from history"
              style={tileCloseButtonStyle}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.background =
                  "rgba(26, 26, 26, 0.08)";
                (e.currentTarget as HTMLButtonElement).style.color = INK;
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.background =
                  "transparent";
                (e.currentTarget as HTMLButtonElement).style.color =
                  "rgba(26, 26, 26, 0.4)";
              }}
            >
              <CloseIcon size={10} />
            </button>
          </div>
        );
      })}
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Asset tile — visual distinct: image-led with a small label below
// ────────────────────────────────────────────────────────────────────

const tileCloseButtonStyle: React.CSSProperties = {
  position: "absolute",
  top: 4,
  right: 4,
  width: 16,
  height: 16,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  border: "none",
  borderRadius: 999,
  background: "transparent",
  color: "rgba(26, 26, 26, 0.4)",
  cursor: "pointer",
};

interface AssetTileProps {
  asset: AssetGeneration;
  onPick: (asset: AssetGeneration) => void;
  onRemove: (id: string) => void;
}

function AssetTile({ asset, onPick, onRemove }: AssetTileProps) {
  return (
    <div
      role="group"
      style={{
        position: "relative",
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        gap: 2,
        padding: "6px 22px 6px 6px",
        borderRadius: 10,
        background: "rgba(26, 26, 26, 0.04)",
        border: "1px solid rgba(255, 90, 31, 0.18)",
        flexShrink: 0,
      }}
    >
      <button
        type="button"
        onClick={() => onPick(asset)}
        title={`Place "${asset.label}" in the scene`}
        style={{
          background: "transparent",
          border: "none",
          padding: 0,
          cursor: "pointer",
          textAlign: "left",
          fontFamily: UI_FONT,
          display: "flex",
          flexDirection: "column",
          gap: 4,
          alignItems: "flex-start",
        }}
      >
        {/* Thumbnail — Flux's intermediate 2D image. We render via an
            <img> tag rather than CSS background-image so the alt text
            describes the asset for screen readers. */}
        {asset.imageUrl ? (
          <img
            src={asset.imageUrl}
            alt={asset.label}
            style={{
              width: 56,
              height: 56,
              borderRadius: 6,
              objectFit: "cover",
              background: "rgba(26, 26, 26, 0.06)",
              flexShrink: 0,
            }}
          />
        ) : (
          // No imageUrl on this asset — render a colored block at the
          // same size so the layout doesn't shift.
          <div
            style={{
              width: 56,
              height: 56,
              borderRadius: 6,
              background: "rgba(255, 90, 31, 0.18)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: 18,
              color: ACCENT,
            }}
            aria-label={asset.label}
          >
            +
          </div>
        )}
        <div
          style={{
            fontSize: 10,
            fontWeight: 500,
            color: INK,
            maxWidth: 64,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
          }}
        >
          {asset.label}
        </div>
        <div
          style={{
            fontSize: 9,
            color: "rgba(26, 26, 26, 0.5)",
            fontWeight: 500,
          }}
        >
          {relativeTime(asset.createdAt)}
        </div>
      </button>
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          onRemove(asset.id);
        }}
        aria-label={`Remove ${asset.label} from history`}
        title="Remove from history"
        style={tileCloseButtonStyle}
        onMouseEnter={(e) => {
          (e.currentTarget as HTMLButtonElement).style.background =
            "rgba(26, 26, 26, 0.08)";
          (e.currentTarget as HTMLButtonElement).style.color = INK;
        }}
        onMouseLeave={(e) => {
          (e.currentTarget as HTMLButtonElement).style.background =
            "transparent";
          (e.currentTarget as HTMLButtonElement).style.color =
            "rgba(26, 26, 26, 0.4)";
        }}
      >
        <CloseIcon size={10} />
      </button>
    </div>
  );
}
